{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "\n",
    "from supermechs.ext.platform import json_decoder\n",
    "\n",
    "BASE_PATH = Path() / \"data\"\n",
    "\n",
    "data = json_decoder((BASE_PATH / \"invalid_item_v3.json\").read_bytes())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  + Exception Group Traceback (most recent call last):\n",
      "  |   File \"/home/eneg/projects/supermechs/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "  |     exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  |   File \"/tmp/ipykernel_185254/210100542.py\", line 4, in <module>\n",
      "  |     to_item_data(data, PackKey(\"@Eneg\"))\n",
      "  |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/items.py\", line 70, in to_item_data\n",
      "  |     catch.checkpoint(\"Problems while parsing item data:\")\n",
      "  |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/exceptions.py\", line 48, in checkpoint\n",
      "  |     raise DataErrorGroup(msg, self.issues) from None\n",
      "  | exceptiongroup.ExceptionGroup: Problems while parsing item data: (2 sub-exceptions)\n",
      "  +-+---------------- 1 ----------------\n",
      "    | Exception Group Traceback (most recent call last):\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/items.py\", line 64, in to_item_data\n",
      "    |     id, name, type_, element = assert_keys(\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 170, in assert_keys\n",
      "    |     catch.checkpoint()\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/exceptions.py\", line 48, in checkpoint\n",
      "    |     raise DataErrorGroup(msg, self.issues) from None\n",
      "    | exceptiongroup.ExceptionGroup:  (2 sub-exceptions)\n",
      "    +-+---------------- 1 ----------------\n",
      "      | Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 166, in assert_keys\n",
      "      |     value = assert_key(type_, mapping, key, at=at)\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 150, in assert_key\n",
      "      |     return assert_type(type_, value, at=(*at, key))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 95, in assert_type\n",
      "      |     return typing.cast(T, assert_enum(base_type, obj, at=at))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 132, in assert_enum\n",
      "      |     raise DataTypeError(obj, enum, at=at) from None\n",
      "      | supermechs.ext.deserializers.exceptions.DataTypeError: At type: Expected one of TORSO, LEGS, DRONE, SIDE_WEAPON, TOP_WEAPON, TELEPORTER, CHARGE, HOOK, SHIELD, PERK, MODULE, got 'SIDE_WEAP'\n",
      "      +---------------- 2 ----------------\n",
      "      | Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 166, in assert_keys\n",
      "      |     value = assert_key(type_, mapping, key, at=at)\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 150, in assert_key\n",
      "      |     return assert_type(type_, value, at=(*at, key))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 95, in assert_type\n",
      "      |     return typing.cast(T, assert_enum(base_type, obj, at=at))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 132, in assert_enum\n",
      "      |     raise DataTypeError(obj, enum, at=at) from None\n",
      "      | supermechs.ext.deserializers.exceptions.DataTypeError: At element: Expected one of PHYSICAL, EXPLOSIVE, ELECTRIC, COMBINED, UNKNOWN, got 'EXPLOSIV'\n",
      "      +------------------------------------\n",
      "    +---------------- 2 ----------------\n",
      "    | Exception Group Traceback (most recent call last):\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/items.py\", line 68, in to_item_data\n",
      "    |     start_stage = to_transform_stages(data, at=at)\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 167, in to_transform_stages\n",
      "    |     catch.checkpoint()\n",
      "    |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/exceptions.py\", line 48, in checkpoint\n",
      "    |     raise DataErrorGroup(msg, self.issues) from None\n",
      "    | exceptiongroup.ExceptionGroup:  (4 sub-exceptions)\n",
      "    +-+---------------- 1 ----------------\n",
      "      | Exception Group Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 148, in to_transform_stages\n",
      "      |     rolling_stats |= to_stats_mapping(base_tier_data, at=(*at, key))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 108, in to_stats_mapping\n",
      "      |     catch.checkpoint(\"Problems while parsing stat mapping:\")\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/exceptions.py\", line 48, in checkpoint\n",
      "      |     raise DataErrorGroup(msg, self.issues) from None\n",
      "      | exceptiongroup.ExceptionGroup: Problems while parsing stat mapping: (3 sub-exceptions)\n",
      "      +-+---------------- 1 ----------------\n",
      "        | supermechs.ext.deserializers.exceptions.DataTypeError: At legendary.expDmg: Expected an array […], got an array […]\n",
      "        +---------------- 2 ----------------\n",
      "        | supermechs.ext.deserializers.exceptions.DataTypeError: At legendary.range: Expected an array […], got an array […]\n",
      "        +---------------- 3 ----------------\n",
      "        | supermechs.ext.deserializers.exceptions.DataTypeError: At legendary.heaCost: Expected an integer, got a string \"…\"\n",
      "        +------------------------------------\n",
      "      +---------------- 2 ----------------\n",
      "      | Exception Group Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 148, in to_transform_stages\n",
      "      |     rolling_stats |= to_stats_mapping(base_tier_data, at=(*at, key))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 108, in to_stats_mapping\n",
      "      |     catch.checkpoint(\"Problems while parsing stat mapping:\")\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/exceptions.py\", line 48, in checkpoint\n",
      "      |     raise DataErrorGroup(msg, self.issues) from None\n",
      "      | exceptiongroup.ExceptionGroup: Problems while parsing stat mapping: (1 sub-exception)\n",
      "      +-+---------------- 1 ----------------\n",
      "        | supermechs.ext.deserializers.exceptions.DataValueError: At mythical: Unknown extra keys: 'is it?'\n",
      "        +------------------------------------\n",
      "      +---------------- 3 ----------------\n",
      "      | Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 155, in to_transform_stages\n",
      "      |     max_level_data = assert_key(RawStatsMapping, data, max_key, at=at)\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 150, in assert_key\n",
      "      |     return assert_type(type_, value, at=(*at, key))\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 98, in assert_type\n",
      "      |     raise DataTypeError(type(obj), base_type, at=at) from None\n",
      "      | supermechs.ext.deserializers.exceptions.DataTypeError: At max_mythical: Expected an object {…}, got an array […]\n",
      "      +---------------- 4 ----------------\n",
      "      | Traceback (most recent call last):\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/stats.py\", line 147, in to_transform_stages\n",
      "      |     base_tier_data = assert_key(RawStatsMapping, data, key, at=at)\n",
      "      |   File \"/home/eneg/projects/supermechs/src/supermechs/ext/deserializers/utils.py\", line 148, in assert_key\n",
      "      |     raise DataKeyError(key, at=at) from None\n",
      "      | supermechs.ext.deserializers.exceptions.DataKeyError: Mapping is missing a required key: 'divine'\n",
      "      +------------------------------------\n"
     ]
    }
   ],
   "source": [
    "from supermechs.abc.item_pack import PackKey\n",
    "from supermechs.ext.deserializers import to_item_data\n",
    "\n",
    "to_item_data(data, PackKey(\"@Eneg\"))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
